from django.urls import path

from optivedge_integrations.integrations.views import (
    ApplianceGroupSnapshotView,
    CollectionScriptView,
    DeveloperView,
    EnforcementPointAddressListView,
    EnforcementPointDetailView,
    EnforcementPointScopeToggleView,
    EnforcementPointZoneDetailView,
    ManagementStationBulkInScopeSyncView,
    ManagementStationCreateView,
    ManagementStationDeleteView,
    ManagementStationDetailView,
    ManagementStationInScopeSyncView,
    ManagementStationListView,
    ManagementStationRefreshDynamicContentView,
    ManagementStationRenormalizeView,
    ManagementStationSyncView,
    ManagementStationUpdateView,
    NoteCreateView,
    NoteListView,
    NormalizationIssueListView,
    NoteUpdateView,
    PolicyObjectCensusCaptureView,
)

urlpatterns = [
    path(
        "collection-script/",
        CollectionScriptView.as_view(),
        name="collection_script",
    ),
    # Hidden operations page - intentionally not registered in app_meta.py's sidebar.
    path("developer/", DeveloperView.as_view(), name="developer"),
    # Reachable from the shell health indicator, which is the only thing that links here.
    path(
        "normalization-issues/",
        NormalizationIssueListView.as_view(),
        name="normalization_issue_list",
    ),
    path(
        "developer/policy-object-census/capture/",
        PolicyObjectCensusCaptureView.as_view(),
        name="policy_object_census_capture",
    ),
    path(
        "management-stations/",
        ManagementStationListView.as_view(),
        name="management_station_list",
    ),
    # Unlinked from every page by decision - see CLAUDE.md "Views". Kept for a hidden view.
    path(
        "management-stations/sync-in-scope-all/",
        ManagementStationBulkInScopeSyncView.as_view(),
        name="management_station_bulk_in_scope_sync",
    ),
    path(
        "management-stations/create/",
        ManagementStationCreateView.as_view(),
        name="management_station_create",
    ),
    path(
        "management-stations/<int:pk>/",
        ManagementStationDetailView.as_view(),
        name="management_station_detail",
    ),
    path(
        "management-stations/<int:pk>/edit/",
        ManagementStationUpdateView.as_view(),
        name="management_station_update",
    ),
    path(
        "management-stations/<int:pk>/delete/",
        ManagementStationDeleteView.as_view(),
        name="management_station_delete",
    ),
    path(
        "management-stations/<int:pk>/sync/",
        ManagementStationSyncView.as_view(),
        name="management_station_sync",
    ),
    path(
        "management-stations/<int:pk>/sync-in-scope/",
        ManagementStationInScopeSyncView.as_view(),
        name="management_station_in_scope_sync",
    ),
    path(
        "management-stations/<int:pk>/renormalize/",
        ManagementStationRenormalizeView.as_view(),
        name="management_station_renormalize",
    ),
    # Unlinked from every page by decision - see CLAUDE.md "Views". Kept for a hidden view.
    path(
        "management-stations/<int:pk>/refresh-dynamic-content/",
        ManagementStationRefreshDynamicContentView.as_view(),
        name="management_station_refresh_dynamic_content",
    ),
    # Unlinked from every page by decision - see CLAUDE.md "Views". Kept for a hidden view.
    path(
        "management-stations/<int:pk>/appliance-groups/<int:appliance_group_pk>/snapshots/",
        ApplianceGroupSnapshotView.as_view(),
        name="appliance_group_snapshots",
    ),
    path(
        "management-stations/<int:pk>/enforcement-points/<int:enforcement_point_pk>/scope/",
        EnforcementPointScopeToggleView.as_view(),
        name="enforcement_point_scope_toggle",
    ),
    # Unlinked from every page by decision - see CLAUDE.md "Views". Kept for a hidden view.
    path(
        "management-stations/<int:pk>/enforcement-points/<int:enforcement_point_pk>/addresses/",
        EnforcementPointAddressListView.as_view(),
        name="enforcement_point_addresses",
    ),
    path(
        "enforcement-points/<int:pk>/",
        EnforcementPointDetailView.as_view(),
        name="enforcement_point_detail",
    ),
    path(
        "enforcement-points/<int:pk>/zones/<int:zone_pk>/",
        EnforcementPointZoneDetailView.as_view(),
        name="enforcement_point_zone_detail",
    ),
    path(
        "notes/",
        NoteListView.as_view(),
        name="note_list",
    ),
    path(
        "notes/create/",
        NoteCreateView.as_view(),
        name="note_create",
    ),
    path(
        "notes/<int:pk>/edit/",
        NoteUpdateView.as_view(),
        name="note_update",
    ),
]
