# Generated by Django 6.0.6 on 2026-06-26 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=64)),
                ('provenance_type', models.CharField(choices=[('local', 'Local'), ('template', 'Template'), ('device_group', 'Device Group'), ('panorama', 'Panorama'), ('unknown', 'Unknown')], max_length=32)),
                ('raw_key', models.CharField(blank=True, max_length=32)),
                ('raw_value', models.CharField(blank=True, max_length=128)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='integration_content_0f5e27_idx'), models.Index(fields=['content_type', 'object_id', 'field_name'], name='integration_content_2d39d3_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'field_name'), name='integrations_unique_field_provenance_per_field')],
            },
        ),
    ]
