# Generated by Django 6.0.6 on 2026-06-26 19:41

from django.db import migrations


# field_name → (explicit_field, prov_field)
# explicit_field is None for string fields that only had a _prov column, not an _explicit column.
_FIELD_MAPPINGS = [
    ("ha_enabled",               "ha_enabled_explicit",            "ha_enabled_prov"),
    ("ha_state_sync_enabled",    "ha_state_sync_explicit",         "ha_state_sync_prov"),
    ("ha_link_monitoring_enabled", "ha_link_monitoring_explicit",  "ha_link_monitoring_prov"),
    ("ntp_primary_server",       None,                             "ntp_primary_server_prov"),
    ("ntp_secondary_server",     None,                             "ntp_secondary_server_prov"),
    ("http_disabled",            "http_disabled_explicit",         "http_disabled_prov"),
    ("https_disabled",           "https_disabled_explicit",        "https_disabled_prov"),
    ("telnet_disabled",          "telnet_disabled_explicit",       "telnet_disabled_prov"),
    ("ssh_disabled",             "ssh_disabled_explicit",          "ssh_disabled_prov"),
    ("icmp_disabled",            "icmp_disabled_explicit",         "icmp_disabled_prov"),
    ("snmp_disabled",            "snmp_disabled_explicit",         "snmp_disabled_prov"),
    ("login_banner",             None,                             "login_banner_prov"),
    ("idle_timeout_minutes",     "idle_timeout_explicit",          "idle_timeout_prov"),
]


def migrate_provenance_to_field_provenance(apps, schema_editor):
    from django.contrib.contenttypes.models import ContentType

    DeviceConfigurationProfile = apps.get_model("integrations", "DeviceConfigurationProfile")
    FieldProvenance = apps.get_model("integrations", "FieldProvenance")

    ct, _ = ContentType.objects.using(schema_editor.connection.alias).get_or_create(
        app_label="integrations",
        model="deviceconfigurationprofile",
    )

    rows = []
    for profile in DeviceConfigurationProfile.objects.using(schema_editor.connection.alias).all():
        for field_name, explicit_attr, prov_attr in _FIELD_MAPPINGS:
            prov_value = getattr(profile, prov_attr, "") or ""
            explicit = getattr(profile, explicit_attr, False) if explicit_attr else None

            if not prov_value:
                # prov empty + explicit True: unusual edge case, treat as local
                if explicit is True:
                    rows.append(FieldProvenance(
                        content_type_id=ct.pk,
                        object_id=profile.pk,
                        field_name=field_name,
                        provenance_type="local",
                        raw_key="",
                        raw_value="",
                    ))
                # explicit False or None: field was absent from payload — no row
            elif prov_value == "local":
                rows.append(FieldProvenance(
                    content_type_id=ct.pk,
                    object_id=profile.pk,
                    field_name=field_name,
                    provenance_type="local",
                    raw_key="",
                    raw_value="",
                ))
            else:
                # Non-"local" prov string: assume @ptpl (best effort — scalar_value()
                # previously conflated @ptpl and @loc into one string without recording the key)
                rows.append(FieldProvenance(
                    content_type_id=ct.pk,
                    object_id=profile.pk,
                    field_name=field_name,
                    provenance_type="template",
                    raw_key="@ptpl",
                    raw_value=prov_value,
                ))

    if rows:
        FieldProvenance.objects.using(schema_editor.connection.alias).bulk_create(rows)


def reverse_migrate_provenance(apps, schema_editor):
    # Re-populating the removed columns from FieldProvenance rows is not
    # implemented — this migration is not safely reversible in production.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_add_field_provenance'),
    ]

    operations = [
        migrations.RunPython(
            migrate_provenance_to_field_provenance,
            reverse_migrate_provenance,
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='ha_enabled_explicit',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='ha_enabled_prov',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='ha_link_monitoring_explicit',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='ha_link_monitoring_prov',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='ha_state_sync_explicit',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='ha_state_sync_prov',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='http_disabled_explicit',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='http_disabled_prov',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='https_disabled_explicit',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='https_disabled_prov',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='icmp_disabled_explicit',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='icmp_disabled_prov',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='idle_timeout_explicit',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='idle_timeout_prov',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='login_banner_prov',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='ntp_primary_server_prov',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='ntp_secondary_server_prov',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='snmp_disabled_explicit',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='snmp_disabled_prov',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='ssh_disabled_explicit',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='ssh_disabled_prov',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='telnet_disabled_explicit',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='telnet_disabled_prov',
        ),
    ]
