# Generated by Django 6.0.6 on 2026-06-29 15:42

from django.db import migrations


def _migrate_policy_provenance_forward(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    FieldProvenance = apps.get_model("integrations", "FieldProvenance")
    AddressObject = apps.get_model("integrations", "AddressObject")
    AddressGroup = apps.get_model("integrations", "AddressGroup")
    SecurityRule = apps.get_model("integrations", "SecurityRule")

    ao_ct = ContentType.objects.get_for_model(AddressObject)
    ag_ct = ContentType.objects.get_for_model(AddressGroup)
    sr_ct = ContentType.objects.get_for_model(SecurityRule)

    def _prov_type(raw_prov: str) -> str:
        if not raw_prov or raw_prov == "local" or raw_prov == "literal" or raw_prov == "builtin":
            return "local"
        return "device_group"

    def _raw_key(raw_prov: str) -> str:
        pt = _prov_type(raw_prov)
        if pt == "device_group":
            return "@loc"
        if pt == "template":
            return "@ptpl"
        return ""

    prov_rows = []

    for obj in AddressObject.objects.all():
        for field_name, raw_prov in [
            ("__entry__", obj.provenance),
            ("value", obj.value_prov),
            ("description", obj.description_prov),
        ]:
            if raw_prov:
                prov_rows.append(FieldProvenance(
                    content_type_id=ao_ct.pk,
                    object_id=obj.pk,
                    field_name=field_name,
                    provenance_type=_prov_type(raw_prov),
                    raw_key=_raw_key(raw_prov),
                    raw_value=raw_prov if _prov_type(raw_prov) != "local" else "",
                ))

    for grp in AddressGroup.objects.all():
        for field_name, raw_prov in [
            ("__entry__", grp.provenance),
            ("dynamic_filter", grp.dynamic_filter_prov),
        ]:
            if raw_prov:
                prov_rows.append(FieldProvenance(
                    content_type_id=ag_ct.pk,
                    object_id=grp.pk,
                    field_name=field_name,
                    provenance_type=_prov_type(raw_prov),
                    raw_key=_raw_key(raw_prov),
                    raw_value=raw_prov if _prov_type(raw_prov) != "local" else "",
                ))

    for rule in SecurityRule.objects.all():
        for field_name, raw_prov in [
            ("__entry__", rule.provenance),
            ("action", rule.action_prov),
            ("disabled", rule.disabled_prov),
            ("rule_type", rule.rule_type_prov),
            ("description", rule.description_prov),
            ("log_start", rule.log_start_prov),
            ("log_end", rule.log_end_prov),
            ("log_setting", rule.log_setting_prov),
        ]:
            if raw_prov:
                prov_rows.append(FieldProvenance(
                    content_type_id=sr_ct.pk,
                    object_id=rule.pk,
                    field_name=field_name,
                    provenance_type=_prov_type(raw_prov),
                    raw_key=_raw_key(raw_prov),
                    raw_value=raw_prov if _prov_type(raw_prov) != "local" else "",
                ))

    if prov_rows:
        FieldProvenance.objects.bulk_create(prov_rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_remove_flat_provenance_fields'),
    ]

    operations = [
        migrations.RunPython(
            _migrate_policy_provenance_forward,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='addressgroup',
            name='dynamic_filter_prov',
        ),
        migrations.RemoveField(
            model_name='addressgroup',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='addressobject',
            name='address_type_prov',
        ),
        migrations.RemoveField(
            model_name='addressobject',
            name='description_prov',
        ),
        migrations.RemoveField(
            model_name='addressobject',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='addressobject',
            name='value_prov',
        ),
        migrations.RemoveField(
            model_name='securityrule',
            name='action_prov',
        ),
        migrations.RemoveField(
            model_name='securityrule',
            name='description_prov',
        ),
        migrations.RemoveField(
            model_name='securityrule',
            name='disabled_prov',
        ),
        migrations.RemoveField(
            model_name='securityrule',
            name='log_end_prov',
        ),
        migrations.RemoveField(
            model_name='securityrule',
            name='log_setting_prov',
        ),
        migrations.RemoveField(
            model_name='securityrule',
            name='log_start_prov',
        ),
        migrations.RemoveField(
            model_name='securityrule',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='securityrule',
            name='rule_type_prov',
        ),
    ]
