# Generated by Django 6.0.6 on 2026-07-02 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_remove_addressgroup_dynamic_filter_prov_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_scope', models.CharField(choices=[('station', 'Station'), ('appliance', 'Appliance')], max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=16)),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_runs', to='integrations.managementstation')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterField(
            model_name='addressgroup',
            name='last_sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun'),
        ),
        migrations.AlterField(
            model_name='addressobject',
            name='last_sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='last_sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun'),
        ),
        migrations.AlterField(
            model_name='appliancegroup',
            name='last_sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun'),
        ),
        migrations.AlterField(
            model_name='deviceconfigurationprofile',
            name='last_sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun'),
        ),
        migrations.AlterField(
            model_name='enforcementnode',
            name='last_sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun'),
        ),
        migrations.AlterField(
            model_name='enforcementpoint',
            name='last_sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun'),
        ),
        migrations.AlterField(
            model_name='securityrule',
            name='last_sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun'),
        ),
        migrations.AlterField(
            model_name='securityrulesearchvocabularyentry',
            name='last_sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun'),
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=16)),
                ('stage', models.CharField(blank=True, choices=[('collect', 'Collect'), ('normalize', 'Normalize')], max_length=16)),
                ('reason', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('appliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_events', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_events', to='integrations.appliancegroup')),
                ('enforcement_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_events', to='integrations.enforcementpoint')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_events', to='integrations.managementstation')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='integrations.integrationrun')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['management_station', '-occurred_at'], name='integration_managem_72e59c_idx'), models.Index(fields=['run', '-occurred_at'], name='integration_run_id_260da8_idx')],
            },
        ),
        migrations.DeleteModel(
            name='IntegrationSyncRun',
        ),
    ]
