# Generated by Django 6.0.6 on 2026-07-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_integrationrun_alter_addressgroup_last_sync_run_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationEnvironment',
        ),
    ]
