# Generated by Django 6.0.7 on 2026-07-15 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_delete_applicationenvironment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('namespace_type', models.CharField(choices=[('local_vsys', 'Local VSYS'), ('local_shared', 'Local Shared'), ('panorama_shared', 'Panorama Shared'), ('panorama_device_group', 'Panorama Device Group'), ('pushed_vsys_effective', 'Pushed VSYS Effective'), ('builtin', 'Built-In')], max_length=64)),
                ('namespace_value', models.CharField(max_length=255)),
                ('precedence_rank', models.PositiveIntegerField()),
                ('config_source', models.CharField(choices=[('local', 'Local'), ('pushed_pre', 'Pushed Pre-Rulebase'), ('pushed_post', 'Pushed Post-Rulebase'), ('default', 'Default')], max_length=32)),
                ('raw_region', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name', 'precedence_rank', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='securityruledestinationaddressref',
            name='integrations_valid_destination_address_ref_shape',
        ),
        migrations.RemoveConstraint(
            model_name='securityrulesourceaddressref',
            name='integrations_valid_source_address_ref_shape',
        ),
        migrations.AlterField(
            model_name='securityruledestinationaddressref',
            name='ref_type',
            field=models.CharField(choices=[('address_object', 'Address Object'), ('static_address_group', 'Static Address Group'), ('dynamic_address_group', 'Dynamic Address Group'), ('any', 'Any'), ('region', 'Region')], max_length=32),
        ),
        migrations.AlterField(
            model_name='securityrulesourceaddressref',
            name='ref_type',
            field=models.CharField(choices=[('address_object', 'Address Object'), ('static_address_group', 'Static Address Group'), ('dynamic_address_group', 'Dynamic Address Group'), ('any', 'Any'), ('region', 'Region')], max_length=32),
        ),
        migrations.AddField(
            model_name='region',
            name='enforcement_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='integrations.enforcementpoint'),
        ),
        migrations.AddField(
            model_name='region',
            name='last_sync_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun'),
        ),
        migrations.AddField(
            model_name='region',
            name='management_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='integrations.managementstation'),
        ),
        migrations.AddField(
            model_name='region',
            name='source_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='integrations.snapshot'),
        ),
        migrations.AddField(
            model_name='securityruledestinationaddressref',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.region'),
        ),
        migrations.AddField(
            model_name='securityrulesourceaddressref',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.region'),
        ),
        migrations.AddIndex(
            model_name='securityruledestinationaddressref',
            index=models.Index(fields=['region'], name='integration_region__eeae13_idx'),
        ),
        migrations.AddIndex(
            model_name='securityrulesourceaddressref',
            index=models.Index(fields=['region'], name='integration_region__854e5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='securityruledestinationaddressref',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('address_group__isnull', True), ('address_object__isnull', False), ('ref_type', 'address_object')), models.Q(('address_group__isnull', False), ('address_object__isnull', False), ('ref_type', 'static_address_group')), models.Q(('address_group__isnull', False), ('address_object__isnull', True), ('ref_type', 'dynamic_address_group')), models.Q(('address_group__isnull', True), ('address_object__isnull', False), ('ref_type', 'any')), models.Q(('address_group__isnull', True), ('address_object__isnull', True), ('ref_type', 'region')), _connector='OR'), name='integrations_valid_destination_address_ref_shape'),
        ),
        migrations.AddConstraint(
            model_name='securityrulesourceaddressref',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('address_group__isnull', True), ('address_object__isnull', False), ('ref_type', 'address_object')), models.Q(('address_group__isnull', False), ('address_object__isnull', False), ('ref_type', 'static_address_group')), models.Q(('address_group__isnull', False), ('address_object__isnull', True), ('ref_type', 'dynamic_address_group')), models.Q(('address_group__isnull', True), ('address_object__isnull', False), ('ref_type', 'any')), models.Q(('address_group__isnull', True), ('address_object__isnull', True), ('ref_type', 'region')), _connector='OR'), name='integrations_valid_source_address_ref_shape'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['enforcement_point', 'name', 'precedence_rank'], name='integration_enforce_d54422_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['enforcement_point', 'namespace_type', 'namespace_value'], name='integration_enforce_d57eef_idx'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('enforcement_point', 'name', 'namespace_type', 'namespace_value'), name='integrations_unique_region_per_point_namespace'),
        ),
    ]
