# Generated by Django 6.0.7 on 2026-07-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=16),
        ),
    ]
