# Generated by Django 6.0.7 on 2026-07-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_alter_integrationrun_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='securityrule',
            index=models.Index(fields=['management_station', 'enforcement_point', 'effective_order', 'name', 'id'], name='integration_managem_feffb6_idx'),
        ),
    ]
