# Generated by Django 6.0.5 on 2026-07-23 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_securityrule_integration_managem_feffb6_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressobject',
            name='edl_list_type',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='AddressObjectResolvedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_start_int', models.BigIntegerField()),
                ('ipv4_end_int', models.BigIntegerField()),
                ('collected_at', models.DateTimeField()),
                ('address_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolved_entries', to='integrations.addressobject')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_object_resolved_entries', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['ipv4_start_int', 'id'],
                'indexes': [models.Index(fields=['address_object', 'ipv4_start_int', 'ipv4_end_int'], name='integration_address_9304cc_idx')],
            },
        ),
    ]
