# Generated by Django 6.0.5 on 2026-07-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_edl_list_type_and_resolved_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressobject',
            name='is_synthetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addressobject',
            name='synthetic_kind',
            field=models.CharField(blank=True, choices=[('rule_literal', 'Rule Literal Address'), ('negated_complement', 'Negated Complement')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='securityrule',
            name='negate_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='securityrule',
            name='negate_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addressobject',
            name='address_type',
            field=models.CharField(choices=[('builtin_any', 'Any'), ('edl', 'External Dynamic List'), ('ip_netmask', 'IP Netmask'), ('fqdn', 'FQDN'), ('ip_range', 'IP Range'), ('ip_wildcard', 'IP Wildcard'), ('negated_complement', 'Negated Complement (system-generated)')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='addressobject',
            constraint=models.CheckConstraint(condition=models.Q(('synthetic_kind', ''), ('is_synthetic', True), _connector='OR'), name='integrations_synthetic_kind_requires_is_synthetic'),
        ),
        migrations.AddConstraint(
            model_name='addressobject',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('address_type', 'negated_complement'), _negated=True), ('is_synthetic', True), _connector='OR'), name='integrations_negated_complement_must_be_synthetic'),
        ),
    ]
