# Generated by Django 6.0.6 on 2026-07-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_negate_flags_and_synthetic_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressgroup',
            name='namespace_type',
            field=models.CharField(choices=[('local_vsys', 'Local VSYS'), ('local_shared', 'Local Shared'), ('panorama_shared', 'Panorama Shared'), ('panorama_device_group', 'Panorama Device Group'), ('pushed_vsys_effective', 'Pushed VSYS Effective'), ('builtin', 'Built-In'), ('predefined', 'Predefined')], max_length=64),
        ),
        migrations.AlterField(
            model_name='addressobject',
            name='namespace_type',
            field=models.CharField(choices=[('local_vsys', 'Local VSYS'), ('local_shared', 'Local Shared'), ('panorama_shared', 'Panorama Shared'), ('panorama_device_group', 'Panorama Device Group'), ('pushed_vsys_effective', 'Pushed VSYS Effective'), ('builtin', 'Built-In'), ('predefined', 'Predefined')], max_length=64),
        ),
        migrations.AlterField(
            model_name='region',
            name='namespace_type',
            field=models.CharField(choices=[('local_vsys', 'Local VSYS'), ('local_shared', 'Local Shared'), ('panorama_shared', 'Panorama Shared'), ('panorama_device_group', 'Panorama Device Group'), ('pushed_vsys_effective', 'Pushed VSYS Effective'), ('builtin', 'Built-In'), ('predefined', 'Predefined')], max_length=64),
        ),
    ]
