# Generated by Django 6.0.6 on 2026-08-19 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('zone_type', models.CharField(choices=[('layer3', 'Layer 3'), ('layer2', 'Layer 2'), ('virtual-wire', 'Virtual Wire'), ('tap', 'Tap'), ('tunnel', 'Tunnel'), ('external', 'External'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('enable_user_identification', models.BooleanField(default=False)),
                ('zone_protection_profile', models.CharField(blank=True, max_length=128)),
                ('log_setting', models.CharField(blank=True, max_length=128)),
                ('packet_buffer_protection', models.BooleanField(blank=True, null=True)),
                ('include_acl', models.JSONField(blank=True, default=list)),
                ('exclude_acl', models.JSONField(blank=True, default=list)),
                ('raw_entry', models.JSONField(blank=True, default=dict)),
                ('enforcement_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='integrations.enforcementpoint')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ZoneInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ip_addresses', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveIntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='integrations.zone')),
            ],
            options={
                'ordering': ['position', 'name', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['management_station'], name='integration_managem_d2041c_idx'),
        ),
        migrations.AddIndex(
            model_name='zone',
            index=models.Index(fields=['enforcement_point'], name='integration_enforce_d773b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('enforcement_point', 'name'), name='integrations_unique_zone_per_enforcement_point'),
        ),
        migrations.AddConstraint(
            model_name='zoneinterface',
            constraint=models.UniqueConstraint(fields=('zone', 'name'), name='integrations_unique_zone_interface_per_zone'),
        ),
    ]
