# Generated by Django 6.0.6 on 2026-08-19 22:04

import django.db.models.deletion
from django.db import migrations, models


def clear_scoped_policy_objects(apps, schema_editor):
    """Delete every scoped policy object; a renormalize repopulates them.

    Shared-scope rows previously hung off an enforcement point and there is no way to
    derive their appliance-group owner from the row itself - the information lives in the
    raw Snapshot payload (@loc, and which config node the entry came from), not in the
    normalized data. Backfilling would mean reimplementing classification inside this
    migration, frozen at this revision, which is precisely the anti-pattern that made a
    migration the wrong tool for the earlier precedence fix.

    These rows are fully re-derivable from stored snapshots without contacting a device:
    run "renormalize" for each management station afterwards. Security rules are cleared
    too because their address refs FK to these objects and would otherwise be orphaned;
    the same renormalize rebuilds them.
    """
    for label in ("AddressObject", "AddressGroup", "Region", "SecurityRule"):
        apps.get_model("integrations", label).objects.all().delete()


def noop_reverse(apps, schema_editor):
    """Nothing to restore - the forward step discards derived data only."""


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0014_zone_zoneinterface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressgroup',
            name='appliance_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_groups', to='integrations.appliancegroup'),
        ),
        migrations.AddField(
            model_name='addressobject',
            name='appliance_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_objects', to='integrations.appliancegroup'),
        ),
        migrations.AddField(
            model_name='region',
            name='appliance_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='integrations.appliancegroup'),
        ),
        migrations.AlterField(
            model_name='addressgroup',
            name='enforcement_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_groups', to='integrations.enforcementpoint'),
        ),
        migrations.AlterField(
            model_name='addressobject',
            name='enforcement_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_objects', to='integrations.enforcementpoint'),
        ),
        migrations.AlterField(
            model_name='region',
            name='enforcement_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='integrations.enforcementpoint'),
        ),
        migrations.AddIndex(
            model_name='addressgroup',
            index=models.Index(fields=['appliance_group', 'name', 'precedence_rank'], name='integration_applian_2eb929_idx'),
        ),
        migrations.AddIndex(
            model_name='addressobject',
            index=models.Index(fields=['appliance_group', 'name', 'precedence_rank'], name='integration_applian_a8ddcd_idx'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['appliance_group', 'name', 'precedence_rank'], name='integration_applian_e3d300_idx'),
        ),
        migrations.RunPython(clear_scoped_policy_objects, noop_reverse),
    ]
