# Generated by Django 6.0.6 on 2026-08-24 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_scoped_object_owner_follows_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], max_length=16)),
                ('disposition', models.CharField(choices=[('skipped', 'Skipped'), ('kept', 'Kept')], max_length=16)),
                ('reason', models.TextField()),
                ('node', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('raw_entry', models.JSONField(blank=True, default=dict)),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalization_issues', to='integrations.appliancegroup')),
                ('enforcement_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalization_issues', to='integrations.enforcementpoint')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalization_issues', to='integrations.managementstation')),
            ],
            options={
                'ordering': ['severity', 'kind', 'name', 'id'],
                'indexes': [models.Index(fields=['management_station', 'severity'], name='integration_managem_e21ce6_idx'), models.Index(fields=['enforcement_point', 'severity'], name='integration_enforce_a3f949_idx'), models.Index(fields=['appliance_group', 'severity'], name='integration_applian_30e76e_idx')],
            },
        ),
    ]
