# Generated by Django 6.0.6 on 2026-08-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0016_normalization_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizationissue',
            name='is_consequent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normalizationissue',
            name='related_object_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='normalizationissue',
            index=models.Index(fields=['management_station', 'severity', 'is_consequent'], name='integration_managem_ee08dd_idx'),
        ),
    ]
