# Generated by Django 6.0.6 on 2026-08-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0017_normalization_issue_causality'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='device_exclude_acl',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='zone',
            name='device_include_acl',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='zone',
            name='enable_device_identification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='net_inspection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='prenat_device_identification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='prenat_source_ip_downstream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='prenat_source_policy_lookup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='prenat_user_identification',
            field=models.BooleanField(default=False),
        ),
    ]
