# Generated by Django 6.0.6 on 2026-08-28 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0018_zone_device_exclude_acl_zone_device_include_acl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('plane', models.CharField(choices=[('mgt', 'Management'), ('aux-1', 'Aux-1'), ('aux-2', 'Aux-2'), ('dataplane', 'Data plane')], max_length=16)),
                ('interface_name', models.CharField(blank=True, max_length=64)),
                ('profile_name', models.CharField(blank=True, max_length=64)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_interfaces', to='integrations.appliance')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_interfaces', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_interfaces', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['appliance__hostname', 'plane', 'interface_name'],
            },
        ),
        migrations.CreateModel(
            name='PermittedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('value', models.CharField(max_length=64)),
                ('family', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ipv4_start_int', models.BigIntegerField(blank=True, null=True)),
                ('ipv4_end_int', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('management_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permitted_sources', to='integrations.managementinterface')),
            ],
            options={
                'ordering': ['management_interface', 'position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='managementinterface',
            index=models.Index(fields=['appliance', 'plane'], name='integration_applian_c4fb58_idx'),
        ),
        migrations.AddIndex(
            model_name='managementinterface',
            index=models.Index(fields=['management_station'], name='integration_managem_e56362_idx'),
        ),
        migrations.AddConstraint(
            model_name='managementinterface',
            constraint=models.UniqueConstraint(fields=('appliance', 'plane', 'interface_name'), name='integrations_unique_management_interface_per_appliance_plane'),
        ),
        migrations.AddIndex(
            model_name='permittedsource',
            index=models.Index(fields=['management_interface', 'ipv4_start_int', 'ipv4_end_int'], name='integration_managem_2635a9_idx'),
        ),
        migrations.AddIndex(
            model_name='permittedsource',
            index=models.Index(fields=['family'], name='integration_family_fcad53_idx'),
        ),
        migrations.AddConstraint(
            model_name='permittedsource',
            constraint=models.UniqueConstraint(fields=('management_interface', 'position'), name='integrations_unique_permitted_source_position'),
        ),
    ]
