# Generated by Django 6.0.6 on 2026-08-28 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_managementinterface_permittedsource_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deviceconfigurationprofile',
            name='integration_has_per_5f5d49_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviceconfigurationprofile',
            name='integration_has_unr_d500c8_idx',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='has_permitted_ip_restrictions',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='has_unrestricted_permitted_ips',
        ),
    ]
