# Generated by Django 6.0.6 on 2026-08-31 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0020_drop_profile_permitted_ip_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('http', 'http'), ('https', 'https'), ('ssh', 'ssh'), ('telnet', 'telnet'), ('snmp', 'snmp'), ('icmp', 'icmp'), ('ping', 'ping'), ('response-pages', 'response-pages'), ('http-ocsp', 'http-ocsp'), ('userid-service', 'userid-service'), ('userid-syslog-listener-ssl', 'userid-syslog-listener-ssl'), ('userid-syslog-listener-udp', 'userid-syslog-listener-udp')], max_length=32)),
                ('enabled', models.BooleanField()),
                ('management_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='integrations.managementinterface')),
            ],
            options={
                'ordering': ['management_interface', 'name'],
                'indexes': [models.Index(fields=['name', 'enabled'], name='integration_name_ba14ed_idx')],
                'constraints': [models.UniqueConstraint(fields=('management_interface', 'name'), name='integrations_unique_management_service_per_surface')],
            },
        ),
    ]
