# Generated by Django 6.0.6 on 2026-08-31 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0021_managementservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='http_disabled',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='https_disabled',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='icmp_disabled',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='snmp_disabled',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='ssh_disabled',
        ),
        migrations.RemoveField(
            model_name='deviceconfigurationprofile',
            name='telnet_disabled',
        ),
    ]
