# Generated by Django 6.0.6 on 2026-08-31 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0022_remove_deviceconfigurationprofile_http_disabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('container', models.CharField(max_length=32)),
                ('interface_type', models.CharField(choices=[('layer3', 'Layer 3'), ('layer2', 'Layer 2'), ('virtual-wire', 'Virtual wire'), ('tap', 'Tap'), ('ha', 'HA'), ('aggregate-member', 'Aggregate member'), ('logical', 'Logical'), ('unknown', 'Unknown')], max_length=24)),
                ('aggregate_group', models.CharField(blank=True, max_length=64)),
                ('addressing', models.CharField(choices=[('static', 'Static'), ('dhcp-client', 'DHCP client'), ('pppoe', 'PPPoE'), ('none', 'None')], default='none', max_length=16)),
                ('ipv4_addresses', models.JSONField(blank=True, default=list)),
                ('ipv6_addresses', models.JSONField(blank=True, default=list)),
                ('comment', models.TextField(blank=True)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='integrations.managementstation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='integrations.interface')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['appliance__hostname', 'container', 'name'],
                'indexes': [models.Index(fields=['appliance', 'container'], name='integration_applian_602fa4_idx'), models.Index(fields=['appliance', 'interface_type'], name='integration_applian_fb8a8f_idx'), models.Index(fields=['management_station'], name='integration_managem_85ec8d_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance', 'name'), name='integrations_unique_interface_per_appliance')],
            },
        ),
    ]
