# Generated by Django 6.0.6 on 2026-08-31 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0023_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizationissue',
            name='appliance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalization_issues', to='integrations.appliance'),
        ),
        migrations.AddIndex(
            model_name='normalizationissue',
            index=models.Index(fields=['appliance', 'severity'], name='integration_applian_0362da_idx'),
        ),
    ]
