# Generated by Django 6.0.6 on 2026-08-31 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0024_normalizationissue_appliance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceManagementProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('bound_interface_names', models.JSONField(blank=True, default=list)),
                ('bound_interface_count', models.PositiveIntegerField(default=0)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_management_profiles', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interface_management_profiles', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_management_profiles', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_management_profiles', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['appliance__hostname', 'name'],
                'indexes': [models.Index(fields=['appliance', 'bound_interface_count'], name='integration_applian_573c23_idx'), models.Index(fields=['management_station'], name='integration_managem_1c1e41_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance', 'name'), name='integrations_unique_interface_mgmt_profile_per_appliance')],
            },
        ),
    ]
