# Generated by Django 6.0.6 on 2026-08-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0025_interfacemanagementprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='management_profile_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
