# Generated by Django 6.0.6 on 2026-08-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0026_interface_management_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='interface_type',
            field=models.CharField(choices=[('layer3', 'Layer 3'), ('layer2', 'Layer 2'), ('virtual-wire', 'Virtual wire'), ('tap', 'Tap'), ('ha', 'HA'), ('aggregate-member', 'Aggregate member'), ('logical', 'Logical'), ('unconfigured', 'Unconfigured'), ('unknown', 'Unknown')], max_length=24),
        ),
    ]
