# Generated by Django 6.0.6 on 2026-09-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0027_alter_interface_interface_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementinterface',
            name='provenance',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='managementservice',
            name='provenance',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='permittedsource',
            name='provenance',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
