# Generated by Django 6.0.6 on 2026-09-01 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0028_managementinterface_provenance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managementinterface',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='managementservice',
            name='provenance',
        ),
        migrations.RemoveField(
            model_name='permittedsource',
            name='provenance',
        ),
    ]
