# Generated by Django 6.0.6 on 2026-09-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0029_remove_managementinterface_provenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='ack_login_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='log_on_high_dp_load',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='server_verification_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
