# Generated by Django 6.0.6 on 2026-09-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0030_deviceconfigurationprofile_ack_login_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='ssl_tls_certificate_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='ssl_tls_max_version',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='ssl_tls_min_version',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='ssl_tls_profile_scope',
            field=models.CharField(blank=True, choices=[('predefined', 'Predefined'), ('shared', 'Shared'), ('unresolved', 'Unresolved')], max_length=16),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='ssl_tls_service_profile_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
