# Generated by Django 6.0.6 on 2026-09-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0031_profile_ssl_tls_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='ssl_tls_certificate_issuer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='ssl_tls_certificate_scope',
            field=models.CharField(blank=True, choices=[('predefined', 'Predefined'), ('shared', 'Shared'), ('unresolved', 'Unresolved')], max_length=16),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='ssl_tls_certificate_trust',
            field=models.CharField(blank=True, choices=[('self_signed', 'Self-signed'), ('ca_issued', 'CA-issued'), ('undetermined', 'Undetermined')], max_length=16),
        ),
    ]
