# Generated by Django 6.0.6 on 2026-09-02 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0032_deviceconfigurationprofile_ssl_tls_certificate_issuer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('shared', 'Shared'), ('vsys', 'Vsys'), ('predefined', 'Predefined')], default='shared', max_length=16)),
                ('vsys_name', models.CharField(blank=True, max_length=64)),
                ('use_crl', models.BooleanField(default=False)),
                ('use_ocsp', models.BooleanField(default=False)),
                ('block_expired_cert', models.BooleanField(default=False)),
                ('block_unknown_cert', models.BooleanField(default=False)),
                ('block_timeout_cert', models.BooleanField(default=False)),
                ('block_unauthenticated_cert', models.BooleanField(default=False)),
                ('crl_receive_timeout', models.PositiveIntegerField(default=5)),
                ('ocsp_receive_timeout', models.PositiveIntegerField(default=5)),
                ('cert_status_timeout', models.PositiveIntegerField(default=5)),
                ('ca_certificate_names', models.JSONField(blank=True, default=list)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['appliance__hostname', 'scope', 'name'],
                'indexes': [models.Index(fields=['appliance', 'use_crl', 'use_ocsp'], name='integration_applian_904597_idx'), models.Index(fields=['management_station'], name='integration_managem_0091ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance', 'scope', 'vsys_name', 'name'), name='integrations_unique_certificate_profile_per_scope')],
            },
        ),
        migrations.CreateModel(
            name='SslTlsServiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('shared', 'Shared'), ('vsys', 'Vsys'), ('predefined', 'Predefined')], default='shared', max_length=16)),
                ('vsys_name', models.CharField(blank=True, max_length=64)),
                ('certificate_name', models.CharField(blank=True, max_length=255)),
                ('min_version', models.CharField(blank=True, max_length=16)),
                ('max_version', models.CharField(blank=True, max_length=16)),
                ('protocol_algorithms', models.JSONField(blank=True, default=dict)),
                ('explicit_algorithms', models.JSONField(blank=True, default=list)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['appliance__hostname', 'scope', 'name'],
                'indexes': [models.Index(fields=['appliance', 'min_version'], name='integration_applian_41429e_idx'), models.Index(fields=['management_station'], name='integration_managem_b7de03_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance', 'scope', 'vsys_name', 'name'), name='integrations_unique_ssl_tls_profile_per_scope')],
            },
        ),
    ]
