# Generated by Django 6.0.6 on 2026-09-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0033_certificateprofile_ssltlsserviceprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='master_key_auto_renew_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='master_key_expires_at',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='master_key_on_hsm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='master_key_state',
            field=models.CharField(blank=True, choices=[('default', 'Factory default'), ('set', 'Set'), ('undetermined', 'Undetermined')], max_length=16),
        ),
    ]
