# Generated by Django 6.0.6 on 2026-09-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0034_profile_master_key_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssltlsserviceprofile',
            name='allows_sha1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='ssltlsserviceprofile',
            index=models.Index(fields=['appliance', 'allows_sha1'], name='integration_applian_7a2ebd_idx'),
        ),
    ]
