# Generated by Django 6.0.6 on 2026-09-03 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0035_ssltlsserviceprofile_allows_sha1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('shared', 'Shared'), ('vsys', 'Vsys'), ('predefined', 'Predefined')], default='shared', max_length=16)),
                ('vsys_name', models.CharField(blank=True, max_length=64)),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=512)),
                ('issuer', models.CharField(blank=True, max_length=512)),
                ('subject_hash', models.CharField(blank=True, max_length=64)),
                ('issuer_hash', models.CharField(blank=True, max_length=64)),
                ('is_self_signed', models.BooleanField(default=False)),
                ('is_ca', models.BooleanField(default=False)),
                ('not_valid_before', models.DateTimeField(blank=True, null=True)),
                ('not_valid_after', models.DateTimeField(blank=True, null=True)),
                ('key_algorithm', models.CharField(blank=True, max_length=32)),
                ('key_size_bits', models.PositiveIntegerField(blank=True, null=True)),
                ('signature_algorithm', models.CharField(blank=True, max_length=64)),
                ('parse_error', models.CharField(blank=True, max_length=255)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['appliance__hostname', 'scope', 'name'],
                'indexes': [models.Index(fields=['appliance', 'not_valid_after'], name='integration_applian_335e02_idx'), models.Index(fields=['appliance', 'key_algorithm', 'key_size_bits'], name='integration_applian_99deb9_idx'), models.Index(fields=['appliance', 'signature_algorithm'], name='integration_applian_323fac_idx'), models.Index(fields=['management_station'], name='integration_managem_814fc7_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance', 'scope', 'vsys_name', 'name'), name='integrations_unique_certificate_per_scope')],
            },
        ),
    ]
