# Generated by Django 6.0.6 on 2026-09-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0036_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_block_repeated_characters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_block_username_inclusion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_change_on_first_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_change_period_block',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_complexity_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_expiration_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_expiration_warning_period',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_history_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_minimum_length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_minimum_lowercase',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_minimum_numeric',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_minimum_special',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_minimum_uppercase',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_new_differs_by_characters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_post_expiration_admin_login_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='password_post_expiration_grace_period',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
