# Generated by Django 6.0.6 on 2026-09-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0037_profile_password_policy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='admin_lockout_failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='admin_lockout_time_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deviceconfigurationprofile',
            name='api_key_lifetime_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
