# Generated by Django 6.0.6 on 2026-09-04 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0038_admin_lockout_and_api_key_lifetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('shared', 'Shared'), ('vsys', 'Vsys'), ('predefined', 'Predefined')], default='shared', max_length=16)),
                ('vsys_name', models.CharField(blank=True, max_length=64)),
                ('method', models.CharField(blank=True, choices=[('none', 'None'), ('local-database', 'Local database'), ('cloud', 'Cloud Authentication Service'), ('radius', 'RADIUS'), ('tacplus', 'TACACS+'), ('ldap', 'LDAP'), ('kerberos', 'Kerberos'), ('saml-idp', 'SAML')], max_length=32)),
                ('lockout_failed_attempts', models.PositiveIntegerField(default=0)),
                ('lockout_time_minutes', models.PositiveIntegerField(default=0)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('mfa_factor_count', models.PositiveIntegerField(default=0)),
                ('mfa_factor_names', models.JSONField(blank=True, default=list)),
                ('allow_list_members', models.JSONField(blank=True, default=list)),
                ('allow_list_count', models.PositiveIntegerField(default=0)),
                ('user_domain', models.CharField(blank=True, max_length=64)),
                ('username_modifier', models.CharField(blank=True, max_length=64)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['management_station__hostname', 'appliance__hostname', 'scope', 'vsys_name', 'name'],
                'indexes': [models.Index(fields=['appliance', 'scope'], name='integration_applian_827694_idx'), models.Index(fields=['name'], name='integration_name_538bca_idx'), models.Index(fields=['method'], name='integration_method_0615b1_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance', 'scope', 'vsys_name', 'name'), name='unique_authentication_profile_per_scope')],
            },
        ),
    ]
