# Generated by Django 6.0.6 on 2026-09-05 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0039_authentication_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('expiration_period', models.PositiveIntegerField(default=0)),
                ('expiration_warning_period', models.PositiveIntegerField(default=0)),
                ('post_expiration_admin_login_count', models.PositiveIntegerField(default=0)),
                ('post_expiration_grace_period', models.PositiveIntegerField(default=0)),
                ('global_expiration_period', models.PositiveIntegerField(default=0)),
                ('weakens_global_expiration', models.BooleanField(default=False)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_profiles', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_profiles', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_profiles', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_profiles', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['management_station__hostname', 'appliance__hostname', 'name'],
                'indexes': [models.Index(fields=['appliance'], name='integration_applian_10d19a_idx'), models.Index(fields=['name'], name='integration_name_5826fa_idx'), models.Index(fields=['weakens_global_expiration'], name='integration_weakens_2426cf_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance', 'name'), name='unique_password_profile_per_appliance')],
            },
        ),
    ]
