# Generated by Django 6.0.6 on 2026-09-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0040_password_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfigurationprofile',
            name='ssl_tls_certificate_trust',
            field=models.CharField(blank=True, choices=[('self_signed', 'Self-signed'), ('private_ca', 'Issued by a private CA on this device'), ('ca_issued', 'CA-issued'), ('undetermined', 'Undetermined')], max_length=16),
        ),
    ]
