# Generated by Django 6.0.5 on 2026-09-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0041_certificate_trust_private_ca'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('role_type', models.CharField(choices=[('superuser', 'Superuser'), ('superreader', 'Superuser (read-only)'), ('deviceadmin', 'Device administrator'), ('devicereader', 'Device administrator (read-only)'), ('vsysadmin', 'Virtual system administrator'), ('vsysreader', 'Virtual system administrator (read-only)'), ('custom', 'Role based'), ('none', 'No role')], default='none', max_length=16)),
                ('role_scope', models.CharField(blank=True, max_length=255)),
                ('custom_role_profile', models.CharField(blank=True, max_length=64)),
                ('is_superuser', models.BooleanField(default=False)),
                ('superuser_cohort_size', models.PositiveIntegerField(default=0)),
                ('authentication_profile_name', models.CharField(blank=True, max_length=64)),
                ('password_profile_name', models.CharField(blank=True, max_length=64)),
                ('client_certificate_only', models.BooleanField(default=False)),
                ('has_password', models.BooleanField(default=False)),
                ('has_public_key', models.BooleanField(default=False)),
                ('uses_local_credentials_only', models.BooleanField(default=False)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_users', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_users', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_users', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_users', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['management_station__hostname', 'appliance__hostname', 'name'],
                'indexes': [models.Index(fields=['appliance'], name='integration_applian_2f652e_idx'), models.Index(fields=['name'], name='integration_name_debff0_idx'), models.Index(fields=['is_superuser'], name='integration_is_supe_850663_idx'), models.Index(fields=['uses_local_credentials_only'], name='integration_uses_lo_c1e320_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance', 'name'), name='unique_admin_user_per_appliance')],
            },
        ),
    ]
