# Generated by Django 6.0.5 on 2026-09-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0042_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='admin_mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='admin_mfa_factors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='authentication_binding',
            field=models.CharField(choices=[('user', 'Per-account'), ('device', 'Device-wide'), ('none', 'Local database')], default='none', max_length=8),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='authentication_profile_unresolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='effective_authentication_profile',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['admin_mfa_enabled'], name='integration_admin_m_96f13d_idx'),
        ),
    ]
