# Generated by Django 6.0.5 on 2026-09-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0043_adminuser_admin_mfa_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adminuser',
            name='integration_uses_lo_c1e320_idx',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='authentication_is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='centrally_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='adminuser',
            index=models.Index(fields=['centrally_authenticated'], name='integration_central_a70c65_idx'),
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='uses_local_credentials_only',
        ),
    ]
