# Generated by Django 6.0.5 on 2026-09-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0044_remove_adminuser_integration_uses_lo_c1e320_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationprofile',
            name='referrer_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authenticationprofile',
            name='referrer_paths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='authenticationprofile',
            index=models.Index(fields=['referrer_count'], name='integration_referre_b32995_idx'),
        ),
    ]
