# Generated by Django 6.0.5 on 2026-09-10 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0045_authenticationprofile_referrer_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(choices=[('shared', 'Shared'), ('vsys', 'Vsys'), ('predefined', 'Predefined')], default='shared', max_length=16)),
                ('vsys_name', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('ldap', 'LDAP'), ('radius', 'RADIUS'), ('tacplus', 'TACACS+'), ('kerberos', 'Kerberos'), ('saml-idp', 'SAML Identity Provider'), ('mfa-server-profile', 'MFA'), ('unknown', 'Unknown')], default='unknown', max_length=24)),
                ('raw_kind', models.CharField(blank=True, max_length=64)),
                ('admin_use_only', models.BooleanField(default=False)),
                ('server_addresses', models.JSONField(blank=True, default=list)),
                ('server_count', models.PositiveIntegerField(default=0)),
                ('ldap_ssl', models.BooleanField(default=True)),
                ('ldap_verify_server_certificate', models.BooleanField(default=False)),
                ('ldap_bind_dn', models.CharField(blank=True, max_length=255)),
                ('ldap_type', models.CharField(blank=True, max_length=32)),
                ('protocol', models.CharField(blank=True, max_length=32)),
                ('saml_validate_idp_certificate', models.BooleanField(default=True)),
                ('saml_want_auth_requests_signed', models.BooleanField(default=True)),
                ('mfa_vendor_type', models.CharField(blank=True, max_length=64)),
                ('certificate_reference', models.CharField(blank=True, max_length=64)),
                ('referrer_paths', models.JSONField(blank=True, default=list)),
                ('referrer_count', models.PositiveIntegerField(default=0)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['management_station__hostname', 'appliance__hostname', 'kind', 'name'],
                'indexes': [models.Index(fields=['appliance', 'scope'], name='integration_applian_5ee130_idx'), models.Index(fields=['kind'], name='integration_kind_af058e_idx'), models.Index(fields=['name'], name='integration_name_d28d7a_idx'), models.Index(fields=['referrer_count'], name='integration_referre_192889_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance', 'scope', 'vsys_name', 'kind', 'name'), name='unique_server_profile_per_scope')],
            },
        ),
    ]
