# Generated by Django 6.0.5 on 2026-09-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0046_serverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationprofile',
            name='allow_list_is_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authenticationprofile',
            name='is_administrative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='authenticationprofile',
            index=models.Index(fields=['is_administrative'], name='integration_is_admi_7a179c_idx'),
        ),
    ]
