# Generated by Django 6.0.6 on 2026-09-10 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0047_authenticationprofile_allow_list_is_all_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordComplexityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('minimum_length', models.PositiveIntegerField(default=0)),
                ('minimum_uppercase', models.PositiveIntegerField(default=0)),
                ('minimum_lowercase', models.PositiveIntegerField(default=0)),
                ('minimum_numeric', models.PositiveIntegerField(default=0)),
                ('minimum_special', models.PositiveIntegerField(default=0)),
                ('block_username_inclusion', models.BooleanField(default=False)),
                ('new_differs_by_characters', models.PositiveIntegerField(default=0)),
                ('history_count', models.PositiveIntegerField(default=0)),
                ('expiration_period', models.PositiveIntegerField(default=0)),
                ('expiration_warning_period', models.PositiveIntegerField(default=0)),
                ('post_expiration_admin_login_count', models.PositiveIntegerField(default=0)),
                ('post_expiration_grace_period', models.PositiveIntegerField(default=0)),
                ('block_repeated_characters', models.PositiveIntegerField(default=0)),
                ('change_on_first_login', models.BooleanField(default=False)),
                ('change_period_block', models.PositiveIntegerField(default=0)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_complexity_policies', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_complexity_policies', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_complexity_policies', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_complexity_policies', to='integrations.snapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['appliance'], name='integration_applian_4d6427_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance',), name='unique_password_complexity_policy_per_appliance')],
            },
        ),
    ]
