# Generated by Django 6.0.6 on 2026-09-10 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0048_passwordcomplexitypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('idle_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('lockout_failed_attempts', models.PositiveIntegerField(default=0)),
                ('lockout_time_minutes', models.PositiveIntegerField(default=0)),
                ('api_key_lifetime_minutes', models.PositiveIntegerField(default=0)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_settings', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authentication_settings', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_settings', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_settings', to='integrations.snapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['appliance'], name='integration_applian_c94838_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance',), name='unique_authentication_settings_per_appliance')],
            },
        ),
    ]
