# Generated by Django 6.0.6 on 2026-09-11 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0051_loggingsettings_masterkey_updateserversettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementTlsBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=64)),
                ('profile_scope', models.CharField(blank=True, choices=[('predefined', 'Predefined'), ('shared', 'Shared'), ('unresolved', 'Unresolved')], max_length=16)),
                ('certificate_trust', models.CharField(blank=True, choices=[('self_signed', 'Self-signed'), ('private_ca', 'Issued by a private CA on this device'), ('ca_issued', 'CA-issued'), ('undetermined', 'Undetermined')], max_length=16)),
                ('certificate_scope', models.CharField(blank=True, choices=[('predefined', 'Predefined'), ('shared', 'Shared'), ('unresolved', 'Unresolved')], max_length=16)),
                ('certificate_issuer', models.CharField(blank=True, max_length=255)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_tls_bindings', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_tls_bindings', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_tls_bindings', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_tls_bindings', to='integrations.snapshot')),
                ('ssl_tls_service_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_bindings', to='integrations.ssltlsserviceprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['appliance'], name='integration_applian_c02aaf_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance',), name='unique_management_tls_binding_per_appliance')],
            },
        ),
    ]
