# Generated by Django 6.0.6 on 2026-09-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0052_managementtlsbinding'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deviceconfigurationprofile',
            name='integration_managem_2ecbec_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviceconfigurationprofile',
            name='integration_applian_b1bb2f_idx',
        ),
        migrations.RemoveIndex(
            model_name='deviceconfigurationprofile',
            name='integration_ha_requ_7702c8_idx',
        ),
        migrations.RemoveConstraint(
            model_name='deviceconfigurationprofile',
            name='integrations_unique_device_configuration_profile_per_appliance',
        ),
        migrations.DeleteModel(
            name='DeviceConfigurationProfile',
        ),
    ]
