# Generated by Django 6.0.6 on 2026-09-11 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0053_delete_deviceconfigurationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='authentication_sequence',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuthenticationSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('shared', 'Shared'), ('vsys', 'Vsys'), ('predefined', 'Predefined')], default='shared', max_length=16)),
                ('vsys_name', models.CharField(blank=True, max_length=64)),
                ('member_names', models.JSONField(blank=True, default=list)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('member_methods', models.JSONField(blank=True, default=list)),
                ('local_member_names', models.JSONField(blank=True, default=list)),
                ('has_local_member', models.BooleanField(default=False)),
                ('unresolved_member_count', models.PositiveIntegerField(default=0)),
                ('all_members_external', models.BooleanField(default=False)),
                ('exit_sequence_on_failure', models.BooleanField(default=False)),
                ('use_domain_find_profile', models.BooleanField(default=True)),
                ('use_userid_domain', models.BooleanField(default=False)),
                ('referrer_paths', models.JSONField(blank=True, default=list)),
                ('referrer_count', models.PositiveIntegerField(default=0)),
                ('is_administrative', models.BooleanField(default=False)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['management_station__hostname', 'appliance__hostname', 'scope', 'vsys_name', 'name'],
                'indexes': [models.Index(fields=['appliance', 'scope'], name='integration_applian_02c60d_idx'), models.Index(fields=['name'], name='integration_name_f55e29_idx'), models.Index(fields=['is_administrative'], name='integration_is_admi_318160_idx'), models.Index(fields=['has_local_member'], name='integration_has_loc_9c8d2b_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance', 'scope', 'vsys_name', 'name'), name='unique_authentication_sequence_per_scope')],
            },
        ),
    ]
