# Generated by Django 6.0.6 on 2026-09-11 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0054_authenticationsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementSshSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=64)),
                ('profile_found', models.BooleanField(default=False)),
                ('ciphers', models.JSONField(blank=True, default=list)),
                ('kex', models.JSONField(blank=True, default=list)),
                ('macs', models.JSONField(blank=True, default=list)),
                ('ciphers_default', models.BooleanField(default=True)),
                ('kex_default', models.BooleanField(default=True)),
                ('macs_default', models.BooleanField(default=True)),
                ('defaults_measured', models.BooleanField(default=False)),
                ('offers_cbc_cipher', models.BooleanField(default=False)),
                ('offers_weak_mac', models.BooleanField(default=False)),
                ('weak_macs', models.JSONField(blank=True, default=list)),
                ('offers_sha1_kex', models.BooleanField(default=False)),
                ('offers_weak_kex', models.BooleanField(default=False)),
                ('offers_sha2_256_mac', models.BooleanField(default=False)),
                ('host_key_type', models.CharField(blank=True, default='RSA', max_length=8)),
                ('host_key_bits', models.PositiveIntegerField(default=2048)),
                ('rekey_interval_seconds', models.PositiveIntegerField(default=0)),
                ('rekey_data_mb', models.PositiveIntegerField(default=0)),
                ('rekey_packets_exponent', models.PositiveIntegerField(default=0)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_ssh_settings', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_ssh_settings', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_ssh_settings', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_ssh_settings', to='integrations.snapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['appliance'], name='integration_applian_83e49e_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance',), name='unique_management_ssh_settings_per_appliance')],
            },
        ),
    ]
