# Generated by Django 6.0.6 on 2026-09-11 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0055_managementsshsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('namespace_type', models.CharField(choices=[('local_vsys', 'Local VSYS'), ('local_shared', 'Local Shared'), ('panorama_shared', 'Panorama Shared'), ('panorama_device_group', 'Panorama Device Group'), ('pushed_vsys_effective', 'Pushed VSYS Effective'), ('builtin', 'Built-In'), ('predefined', 'Predefined')], max_length=64)),
                ('namespace_value', models.CharField(max_length=255)),
                ('precedence_rank', models.PositiveIntegerField()),
                ('config_source', models.CharField(choices=[('local', 'Local'), ('pushed_pre', 'Pushed Pre-Rulebase'), ('pushed_post', 'Pushed Post-Rulebase'), ('default', 'Default')], max_length=32)),
                ('kind', models.CharField(choices=[('spyware', 'Anti-Spyware'), ('vulnerability', 'Vulnerability Protection')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_predefined', models.BooleanField(default=False)),
                ('rule_count', models.PositiveIntegerField(default=0)),
                ('threat_exception_count', models.PositiveIntegerField(default=0)),
                ('critical_blocked', models.BooleanField(default=False)),
                ('critical_detail', models.CharField(blank=True, max_length=255)),
                ('high_blocked', models.BooleanField(default=False)),
                ('high_detail', models.CharField(blank=True, max_length=255)),
                ('medium_blocked', models.BooleanField(default=False)),
                ('medium_detail', models.CharField(blank=True, max_length=255)),
                ('referrer_count', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('referrers', models.JSONField(blank=True, default=list)),
                ('raw_profile', models.JSONField(blank=True, default=dict)),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_profiles', to='integrations.appliancegroup')),
                ('enforcement_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_profiles', to='integrations.enforcementpoint')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_profiles', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_profiles', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['kind', 'name', 'precedence_rank', 'id'],
                'indexes': [models.Index(fields=['enforcement_point', 'kind', 'name', 'precedence_rank'], name='integration_enforce_1fb744_idx'), models.Index(fields=['appliance_group', 'kind', 'name', 'precedence_rank'], name='integration_applian_ae73f6_idx'), models.Index(fields=['enforcement_point', 'namespace_type', 'namespace_value'], name='integration_enforce_6dfcdf_idx')],
                'constraints': [models.UniqueConstraint(fields=('enforcement_point', 'kind', 'name', 'namespace_type', 'namespace_value'), name='integrations_unique_security_profile_per_point_namespace'), models.UniqueConstraint(fields=('appliance_group', 'kind', 'name', 'namespace_type', 'namespace_value'), name='integrations_unique_security_profile_per_group_namespace')],
            },
        ),
        migrations.CreateModel(
            name='SecurityProfileGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('namespace_type', models.CharField(choices=[('local_vsys', 'Local VSYS'), ('local_shared', 'Local Shared'), ('panorama_shared', 'Panorama Shared'), ('panorama_device_group', 'Panorama Device Group'), ('pushed_vsys_effective', 'Pushed VSYS Effective'), ('builtin', 'Built-In'), ('predefined', 'Predefined')], max_length=64)),
                ('namespace_value', models.CharField(max_length=255)),
                ('precedence_rank', models.PositiveIntegerField()),
                ('config_source', models.CharField(choices=[('local', 'Local'), ('pushed_pre', 'Pushed Pre-Rulebase'), ('pushed_post', 'Pushed Post-Rulebase'), ('default', 'Default')], max_length=32)),
                ('spyware_profile', models.CharField(blank=True, max_length=255)),
                ('vulnerability_profile', models.CharField(blank=True, max_length=255)),
                ('members', models.JSONField(blank=True, default=dict)),
                ('raw_group', models.JSONField(blank=True, default=dict)),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_profile_groups', to='integrations.appliancegroup')),
                ('enforcement_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_profile_groups', to='integrations.enforcementpoint')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile_groups', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile_groups', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['name', 'precedence_rank', 'id'],
                'indexes': [models.Index(fields=['enforcement_point', 'name', 'precedence_rank'], name='integration_enforce_244e62_idx'), models.Index(fields=['appliance_group', 'name', 'precedence_rank'], name='integration_applian_380e80_idx')],
                'constraints': [models.UniqueConstraint(fields=('enforcement_point', 'name', 'namespace_type', 'namespace_value'), name='integrations_unique_security_profile_group_per_point_namespace'), models.UniqueConstraint(fields=('appliance_group', 'name', 'namespace_type', 'namespace_value'), name='integrations_unique_security_profile_group_per_group_namespace')],
            },
        ),
    ]
