# Generated by Django 6.0.5 on 2026-09-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0056_securityprofile_securityprofilegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementsshsettings',
            name='ciphers_below_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managementsshsettings',
            name='kex_below_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managementsshsettings',
            name='macs_below_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='managementsshsettings',
            name='non_preferred_ciphers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='managementsshsettings',
            name='non_preferred_kex',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='managementsshsettings',
            name='non_preferred_macs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
