# Generated by Django 6.0.5 on 2026-09-14 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0057_managementsshsettings_ciphers_below_preferred_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NtpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('primary_server', models.CharField(blank=True, max_length=255)),
                ('secondary_server', models.CharField(blank=True, max_length=255)),
                ('server_count', models.PositiveSmallIntegerField(default=0)),
                ('primary_auth_type', models.CharField(choices=[('none', 'None'), ('symmetric-key', 'Symmetric key'), ('autokey', 'Autokey')], default='none', max_length=16)),
                ('secondary_auth_type', models.CharField(blank=True, choices=[('none', 'None'), ('symmetric-key', 'Symmetric key'), ('autokey', 'Autokey')], default='none', max_length=16)),
                ('primary_algorithm', models.CharField(blank=True, max_length=8)),
                ('secondary_algorithm', models.CharField(blank=True, max_length=8)),
                ('all_servers_symmetric_key', models.BooleanField(default=False)),
                ('unauthenticated_servers', models.JSONField(blank=True, default=list)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ntp_settings', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ntp_settings', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ntp_settings', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ntp_settings', to='integrations.snapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['appliance'], name='integration_applian_d2a176_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance',), name='unique_ntp_settings_per_appliance')],
            },
        ),
        migrations.CreateModel(
            name='SnmpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('is_configured', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, choices=[('v2c', 'SNMPv2c'), ('v3', 'SNMPv3')], max_length=4)),
                ('version_implicit', models.BooleanField(default=False)),
                ('uses_v2c', models.BooleanField(default=False)),
                ('community_set', models.BooleanField(default=False)),
                ('community_is_default', models.BooleanField(default=False)),
                ('v3_user_count', models.PositiveSmallIntegerField(default=0)),
                ('v3_view_count', models.PositiveSmallIntegerField(default=0)),
                ('is_exposed', models.BooleanField(default=False)),
                ('exposed_surfaces', models.JSONField(blank=True, default=list)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_settings', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snmp_settings', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_settings', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snmp_settings', to='integrations.snapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['appliance'], name='integration_applian_e4703d_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance',), name='unique_snmp_settings_per_appliance')],
            },
        ),
        migrations.CreateModel(
            name='SystemIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=64)),
                ('hostname_is_factory_default', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('timezone_is_utc', models.BooleanField(default=False)),
                ('addressing_mode', models.CharField(choices=[('static', 'Static'), ('dhcp-client', 'DHCP client')], default='static', max_length=16)),
                ('addressing_mode_explicit', models.BooleanField(default=False)),
                ('accept_dhcp_hostname', models.BooleanField(default=False)),
                ('accept_dhcp_domain', models.BooleanField(default=False)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_identities', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_identities', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_identities', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_identities', to='integrations.snapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['appliance'], name='integration_applian_42804e_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance',), name='unique_system_identity_per_appliance')],
            },
        ),
    ]
