# Generated by Django 6.0.6 on 2026-09-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0059_ssh_below_preferred_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemidentity',
            name='hostname_is_factory_default',
            field=models.BooleanField(default=True),
        ),
    ]
