# Generated by Django 6.0.6 on 2026-09-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0061_provenance_default_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldprovenance',
            name='provenance_type',
            field=models.CharField(choices=[('local', 'Local'), ('template', 'Template'), ('device_group', 'Device Group'), ('panorama', 'Panorama'), ('pan_os_default', 'PAN-OS default'), ('assumed_default', 'Assumed default'), ('not_configured', 'Not configured'), ('unknown', 'Unknown')], max_length=32),
        ),
    ]
