# Generated by Django 6.0.6 on 2026-09-22 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0063_provenance_derived_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('dg_id', models.CharField(blank=True, max_length=32)),
                ('is_shared', models.BooleanField(default=False)),
                ('discovered_from', models.CharField(choices=[('collected', 'Collected from the hierarchy'), ('provenance', 'Seen only in provenance'), ('synthesized', 'Synthesized')], default='collected', max_length=32)),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to='integrations.managementstation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='integrations.devicegroup')),
                ('source_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_groups', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DeviceGroupBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='integrations.devicegroup')),
                ('enforcement_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_group_bindings', to='integrations.enforcementpoint')),
            ],
            options={
                'ordering': ['device_group__name', 'enforcement_point__vsys_name', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='devicegroup',
            index=models.Index(fields=['management_station'], name='integration_managem_e328a6_idx'),
        ),
        migrations.AddIndex(
            model_name='devicegroup',
            index=models.Index(fields=['parent'], name='integration_parent__e19665_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicegroup',
            constraint=models.UniqueConstraint(fields=('management_station', 'name'), name='integrations_unique_device_group_per_station'),
        ),
        migrations.AddIndex(
            model_name='devicegroupbinding',
            index=models.Index(fields=['device_group'], name='integration_device__4add23_idx'),
        ),
        migrations.AddIndex(
            model_name='devicegroupbinding',
            index=models.Index(fields=['enforcement_point'], name='integration_enforce_b67934_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicegroupbinding',
            constraint=models.UniqueConstraint(fields=('device_group', 'enforcement_point'), name='integrations_unique_device_group_binding'),
        ),
    ]
