# Generated by Django 6.0.6 on 2026-09-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0065_prune_orphaned_field_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressobject',
            name='resolved_content_source_total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addressobject',
            name='resolved_content_truncated',
            field=models.BooleanField(default=False),
        ),
    ]
