# Generated by Django 6.0.6 on 2026-10-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0066_address_object_resolved_content_completeness'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityrule',
            name='destination_num_hosts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securityrule',
            name='source_num_hosts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
