# Generated by Django 6.0.6 on 2026-10-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0067_security_rule_address_breadth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementsshsettings',
            name='host_key_bits',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='managementsshsettings',
            name='host_key_type',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
