# Generated by Django 6.0.6 on 2026-10-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0068_alter_managementsshsettings_host_key_bits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityrule',
            name='has_antivirus_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='securityrule',
            name='has_spyware_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='securityrule',
            name='has_vulnerability_profile',
            field=models.BooleanField(default=False),
        ),
    ]
