# Generated by Django 6.0.6 on 2026-10-07 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0069_security_rule_profile_coverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityprofile',
            name='critical_blocked',
        ),
        migrations.RemoveField(
            model_name='securityprofile',
            name='critical_detail',
        ),
        migrations.RemoveField(
            model_name='securityprofile',
            name='high_blocked',
        ),
        migrations.RemoveField(
            model_name='securityprofile',
            name='high_detail',
        ),
        migrations.RemoveField(
            model_name='securityprofile',
            name='medium_blocked',
        ),
        migrations.RemoveField(
            model_name='securityprofile',
            name='medium_detail',
        ),
        migrations.CreateModel(
            name='SecurityProfileSeverityVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium')], max_length=16)),
                ('blocked', models.BooleanField()),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('security_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='severity_verdicts', to='integrations.securityprofile')),
            ],
            options={
                'ordering': ['security_profile', 'severity'],
                'constraints': [models.UniqueConstraint(fields=('security_profile', 'severity'), name='integrations_unique_verdict_per_profile_severity')],
            },
        ),
    ]
