# Generated by Django 6.0.6 on 2026-10-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0070_security_profile_severity_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityprofile',
            name='kind',
            field=models.CharField(choices=[('spyware', 'Anti-Spyware'), ('vulnerability', 'Vulnerability Protection'), ('virus', 'Antivirus')], max_length=16),
        ),
    ]
