# Generated by Django 6.0.6 on 2026-10-07 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0071_security_profile_virus_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityProfileDecoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=32)),
                ('configured_action', models.CharField(max_length=32)),
                ('effective_action', models.CharField(max_length=32)),
                ('blocks', models.BooleanField()),
                ('configured_wildfire_action', models.CharField(blank=True, max_length=32)),
                ('effective_wildfire_action', models.CharField(blank=True, max_length=32)),
                ('wildfire_blocks', models.BooleanField(default=False)),
                ('security_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decoders', to='integrations.securityprofile')),
            ],
            options={
                'ordering': ['security_profile', 'protocol'],
                'constraints': [models.UniqueConstraint(fields=('security_profile', 'protocol'), name='integrations_unique_decoder_per_profile_protocol')],
            },
        ),
    ]
