# Generated by Django 6.0.6 on 2026-10-08 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0072_security_profile_decoder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityProfileMlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('enabled', models.BooleanField()),
                ('configured_action', models.CharField(blank=True, max_length=32)),
                ('security_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='integrations.securityprofile')),
            ],
            options={
                'ordering': ['security_profile', 'name'],
                'constraints': [models.UniqueConstraint(fields=('security_profile', 'name'), name='integrations_unique_ml_model_per_profile')],
            },
        ),
    ]
