# Generated by Django 6.0.6 on 2026-10-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0073_security_profile_ml_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityprofile',
            name='kind',
            field=models.CharField(choices=[('spyware', 'Anti-Spyware'), ('vulnerability', 'Vulnerability Protection'), ('virus', 'Antivirus'), ('wildfire-analysis', 'WildFire Analysis')], max_length=32),
        ),
    ]
