"""A per-application action override defeats a decoder action, so PAN-AVW-001 must see it.

Found 2026-10-08 by enumerating the antivirus profile's key set with `action=complete`: the
`application` node is an entry-keyed per-application action override carrying the same seven
actions as a decoder. A profile can read `reset-both` on all seven decoders and still allow
malware over a named application, and PAN-AVW-001 reported such a profile as hardened.

A NEW MODEL rather than a column on SecurityProfile, deliberately. The checklist's rule is
that a new derived column on an already-populated model reports a CLEAN ESTATE until
re-normalization, because a boolean's `False` default sits on the compliant side. A new model
has no rows until normalization creates them, and no rows is also the correct answer for
almost every profile - an override is an operator-added exception, so the empty case is
genuine rather than stale.

The one state that could still read as compliant-by-accident is a profile row written before
this migration: it has decoder rows and no override rows. `blocks` is nullable so the
unestablished `default` case fires rather than passes, but a pre-existing profile row cannot
be distinguished from a clean one - so the operator sequence matters and is stated in the
control's record: migrate, RENORMALIZE, reseed, regenerate.

Generated by Django 6.0.6 on 2026-10-08.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0075_ml_model_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityProfileApplicationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.CharField(max_length=128)),
                ('configured_action', models.CharField(blank=True, max_length=32)),
                ('blocks', models.BooleanField(null=True)),
                ('security_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_overrides', to='integrations.securityprofile')),
            ],
            options={
                'ordering': ['security_profile', 'application'],
                'constraints': [models.UniqueConstraint(fields=('security_profile', 'application'), name='integrations_unique_app_override_per_profile_application')],
            },
        ),
    ]
