"""The decoder's THIRD action column, which nothing read.

A protocol decoder has three action fields - SIGNATURE ACTION, WILDFIRE SIGNATURE ACTION and
WILDFIRE INLINE ML ACTION - and `default` resolves by the same per-protocol table in all
three. Only the first was collected, and only the first was asserted, so a profile that is
`reset-both` on signature action and `allow` on both WildFire columns passed PAN-AVW-001 while
delivering anything WildFire caught.

`mlav_blocks` IS NULLABLE ON PURPOSE and existing rows are left null rather than backfilled.
There is nothing to backfill from: `mlav-action` was never collected, so no stored row carries
the information, and a value invented here would be a guess scored by a control. Null means
NOT COMPUTED, which the control reports as a gap naming itself - "not yet computed" - so the
window between migrating and re-normalizing announces itself instead of reading as a hardened
estate.

Contrast with 0075, where the backfill WAS exact: `enabled` had been written by a test
equivalent to the new `blocks`, so the old column carried the answer. Here it does not.

Operator sequence: migrate, RENORMALIZE, reseed, regenerate.

Generated by Django 6.0.6 on 2026-10-08.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0076_application_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityprofiledecoder',
            name='configured_mlav_action',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='securityprofiledecoder',
            name='effective_mlav_action',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='securityprofiledecoder',
            name='mlav_blocks',
            field=models.BooleanField(null=True),
        ),
    ]
