"""WildFire analysis: a satellite for the profile's rules, and two columns on the rule.

PAN-AVW-003 asks whether the profile in force on a SECURITY RULE sends every file type for
sandbox analysis. Per rule rather than per profile, because a profile nothing uses endangers
nothing while a rule carries traffic.

`wildfire_analysis_submits_all` IS NULLABLE AND NOT BACKFILLED. Null means either "no profile
reaches this rule" or "nothing has re-normalized this row yet", and both fire. There is
nothing to backfill from - the resolution needs the profile's rules, which this migration also
creates - and a column whose empty value meant "fine" would report a clean estate for the
whole window between migrating and re-normalizing. That window has bitten this project before,
measured on PAN-MCR-001/002/003.

The satellite is a new model, so it has no stale rows at all.

Operator sequence: migrate, RENORMALIZE, reseed, regenerate.

Generated by Django 6.0.6 on 2026-10-09.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0077_decoder_mlav_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityrule',
            name='wildfire_analysis_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='securityrule',
            name='wildfire_analysis_submits_all',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='SecurityProfileWildfireRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('applications', models.JSONField(blank=True, default=list)),
                ('file_types', models.JSONField(blank=True, default=list)),
                ('direction', models.CharField(blank=True, max_length=16)),
                ('analysis', models.CharField(blank=True, max_length=16)),
                ('covers_all_file_types', models.BooleanField(default=False)),
                ('covers_all_applications', models.BooleanField(default=False)),
                ('covers_both_directions', models.BooleanField(null=True)),
                ('security_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildfire_rules', to='integrations.securityprofile')),
            ],
            options={
                'ordering': ['security_profile', 'name'],
                'constraints': [models.UniqueConstraint(fields=('security_profile', 'name'), name='integrations_unique_wildfire_rule_per_profile')],
            },
        ),
    ]
