# Generated by Django 6.0.6 on 2026-10-09 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0078_wildfire_analysis_coverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WildfireSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('size_limits', models.JSONField(blank=True, default=dict)),
                ('untuned_file_types', models.JSONField(blank=True, default=list)),
                ('size_limits_untuned', models.BooleanField(default=True)),
                ('session_info_excluded', models.JSONField(blank=True, default=list)),
                ('inline_session_info_excluded', models.JSONField(blank=True, default=list)),
                ('report_benign_file', models.BooleanField(default=False)),
                ('report_grayware_file', models.BooleanField(default=False)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildfire_settings', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wildfire_settings', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildfire_settings', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wildfire_settings', to='integrations.snapshot')),
            ],
            options={
                'indexes': [models.Index(fields=['appliance'], name='integration_applian_7503c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance',), name='unique_wildfire_settings_per_appliance')],
            },
        ),
    ]
