# Generated by Django 6.0.6 on 2026-10-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0079_wildfire_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildfiresettings',
            name='shares_full_session_info',
            field=models.BooleanField(default=True),
        ),
    ]
