# Generated by Django 6.0.6 on 2026-10-11 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0080_wildfire_full_session_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityProfileInlineDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('configured_action', models.CharField(blank=True, max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('blocks', models.BooleanField(default=False)),
                ('security_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inline_detectors', to='integrations.securityprofile')),
            ],
            options={
                'ordering': ['security_profile', 'name'],
                'constraints': [models.UniqueConstraint(fields=('security_profile', 'name'), name='integrations_unique_inline_detector_per_profile')],
            },
        ),
    ]
