# Generated by Django 6.0.6 on 2026-10-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0081_inline_detectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityprofile',
            name='exception_surfaces',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
