"""PAN-VLN-002: whether a profile blocks a threat category's SOURCE.

A satellite, not columns, for the same reason the severity verdict is one: only a
vulnerability profile answers the question, and a column could only say no about the kinds
that do not. No backfill is needed or possible - every row is computed from the rule list, so
the values appear when the profiles are next normalized and the table is empty until then.

AN EMPTY TABLE READS AS A CLEAN ESTATE, which is why PAN-VLN-002's query asks for
`blocks_source = false` against rows that exist rather than for the absence of a row:
re-normalize before trusting a quiet result from this control.
"""

# Generated by Django 6.0.6 on 2026-10-11 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0082_exception_surfaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityProfileCategoryVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('blocks_source', models.BooleanField()),
                ('weakest_action', models.CharField(blank=True, max_length=32)),
                ('track_by', models.CharField(blank=True, max_length=32)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('security_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_verdicts', to='integrations.securityprofile')),
            ],
            options={
                'ordering': ['security_profile', 'category'],
                'constraints': [models.UniqueConstraint(fields=('security_profile', 'category'), name='integrations_unique_category_verdict_per_profile')],
            },
        ),
    ]
