"""PAN-SPY-002: the DNS signature sources of an anti-spyware profile, and the sinkhole address.

The two address columns default to blank and are NOT backfilled, because the value is read
from config rather than derived - a profile normalized before this migration has no DNS tree
stored in a column, and blank is the honest reading of "nobody has looked yet".

THE SOURCE TABLE IS EMPTY UNTIL RE-NORMALIZATION, and an empty table reads as a clean estate:
PAN-SPY-002 asks for a Palo Alto Networks Content row with `sinkholes = false`, so before the
profiles are re-read it matches nothing and the control is silent for the wrong reason.
Re-normalize before trusting a quiet result.

Rows are written for anti-spyware profiles only - the botnet-domains tree exists on no other
kind - including a SYNTHESIZED row for the Palo Alto Networks Content list when the config
does not name it. See the model docstring: the Help says an unconfigured list sinkholes, that
implicit value is documented rather than measured, and `action_is_implicit` marks every row
resting on it.
"""

# Generated by Django 6.0.6 on 2026-10-11 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0083_category_verdicts'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityprofile',
            name='dns_sinkhole_ipv4',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='securityprofile',
            name='dns_sinkhole_ipv6',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='SecurityProfileDnsSignatureSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_paloalto_content', models.BooleanField(default=False)),
                ('configured_action', models.CharField(blank=True, max_length=32)),
                ('effective_action', models.CharField(blank=True, max_length=32)),
                ('sinkholes', models.BooleanField(default=False)),
                ('action_is_implicit', models.BooleanField(default=False)),
                ('security_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_signature_sources', to='integrations.securityprofile')),
            ],
            options={
                'ordering': ['security_profile', '-is_paloalto_content', 'name'],
                'constraints': [models.UniqueConstraint(fields=('security_profile', 'name'), name='integrations_unique_dns_source_per_profile')],
            },
        ),
    ]
