# Generated by Django 6.0.4 on 2026-04-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressobject',
            name='is_edl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addressobject',
            name='address_type',
            field=models.CharField(choices=[('builtin_any', 'Any'), ('edl', 'External Dynamic List'), ('ip_netmask', 'IP Netmask'), ('fqdn', 'FQDN'), ('ip_range', 'IP Range'), ('ip_wildcard', 'IP Wildcard')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='addressobject',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('address_type', 'edl'), _negated=True), ('is_edl', True), _connector='OR'), name='integrations_edl_address_object_flag'),
        ),
    ]
