# Generated by Django 6.0.4 on 2026-05-01 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_addressobject_is_edl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementPlaneProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('config_source', models.CharField(choices=[('local', 'Local'), ('pushed_pre', 'Pushed Pre-Rulebase'), ('pushed_post', 'Pushed Post-Rulebase'), ('default', 'Default')], max_length=32)),
                ('provenance', models.CharField(blank=True, max_length=128)),
                ('ha_required', models.BooleanField(default=False)),
                ('ha_enabled', models.BooleanField(default=False)),
                ('ha_enabled_explicit', models.BooleanField(default=False)),
                ('ha_enabled_prov', models.CharField(blank=True, max_length=128)),
                ('ha_state_sync_enabled', models.BooleanField(default=False)),
                ('ha_state_sync_explicit', models.BooleanField(default=False)),
                ('ha_state_sync_prov', models.CharField(blank=True, max_length=128)),
                ('ha_link_monitoring_enabled', models.BooleanField(default=False)),
                ('ha_link_monitoring_explicit', models.BooleanField(default=False)),
                ('ha_link_monitoring_prov', models.CharField(blank=True, max_length=128)),
                ('ntp_primary_server', models.CharField(blank=True, max_length=255)),
                ('ntp_primary_server_prov', models.CharField(blank=True, max_length=128)),
                ('ntp_secondary_server', models.CharField(blank=True, max_length=255)),
                ('ntp_secondary_server_prov', models.CharField(blank=True, max_length=128)),
                ('http_disabled', models.BooleanField(default=True)),
                ('http_disabled_explicit', models.BooleanField(default=False)),
                ('http_disabled_prov', models.CharField(blank=True, max_length=128)),
                ('https_disabled', models.BooleanField(default=False)),
                ('https_disabled_explicit', models.BooleanField(default=False)),
                ('https_disabled_prov', models.CharField(blank=True, max_length=128)),
                ('telnet_disabled', models.BooleanField(default=True)),
                ('telnet_disabled_explicit', models.BooleanField(default=False)),
                ('telnet_disabled_prov', models.CharField(blank=True, max_length=128)),
                ('ssh_disabled', models.BooleanField(default=False)),
                ('ssh_disabled_explicit', models.BooleanField(default=False)),
                ('ssh_disabled_prov', models.CharField(blank=True, max_length=128)),
                ('icmp_disabled', models.BooleanField(default=False)),
                ('icmp_disabled_explicit', models.BooleanField(default=False)),
                ('icmp_disabled_prov', models.CharField(blank=True, max_length=128)),
                ('snmp_disabled', models.BooleanField(default=True)),
                ('snmp_disabled_explicit', models.BooleanField(default=False)),
                ('snmp_disabled_prov', models.CharField(blank=True, max_length=128)),
                ('permitted_ip_values', models.JSONField(blank=True, default=list)),
                ('permitted_ip_count', models.PositiveIntegerField(default=0)),
                ('has_permitted_ip_restrictions', models.BooleanField(default=False)),
                ('has_unrestricted_permitted_ips', models.BooleanField(default=False)),
                ('login_banner', models.TextField(blank=True)),
                ('login_banner_prov', models.CharField(blank=True, max_length=128)),
                ('idle_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('idle_timeout_explicit', models.BooleanField(default=False)),
                ('idle_timeout_prov', models.CharField(blank=True, max_length=128)),
                ('raw_profile', models.JSONField(blank=True, default=dict)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_plane_profiles', to='integrations.appliance')),
                ('appliance_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_plane_profiles', to='integrations.appliancegroup')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationsyncrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_plane_profiles', to='integrations.managementstation')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_plane_profiles', to='integrations.snapshot')),
            ],
            options={
                'ordering': ['management_station__hostname', 'appliance__hostname', 'appliance__serial_number'],
                'indexes': [models.Index(fields=['management_station'], name='integration_managem_1f697c_idx'), models.Index(fields=['appliance_group'], name='integration_applian_480f2a_idx'), models.Index(fields=['ha_required'], name='integration_ha_requ_44809c_idx'), models.Index(fields=['has_permitted_ip_restrictions'], name='integration_has_per_953d84_idx'), models.Index(fields=['has_unrestricted_permitted_ips'], name='integration_has_unr_904968_idx')],
                'constraints': [models.UniqueConstraint(fields=('appliance',), name='integrations_unique_management_plane_profile_per_appliance')],
            },
        ),
    ]
