# Generated by Django 6.0.4 on 2026-05-01 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_managementplaneprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityRuleSearchVocabularyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_missing', models.BooleanField(default=False)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('field_family', models.CharField(choices=[('source_address_name', 'Source Address Name'), ('destination_address_name', 'Destination Address Name'), ('application', 'Application'), ('service', 'Service')], max_length=64)),
                ('canonical_value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(blank=True, max_length=255)),
                ('compact_value', models.CharField(blank=True, max_length=255)),
                ('rule_count', models.PositiveIntegerField(default=0)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)ss', to='integrations.integrationsyncrun')),
                ('management_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_rule_search_vocabulary_entries', to='integrations.managementstation')),
            ],
            options={
                'ordering': ['management_station__hostname', 'field_family', '-rule_count', 'canonical_value', 'id'],
                'indexes': [models.Index(fields=['management_station', 'field_family', 'normalized_value'], name='integration_managem_74b9f8_idx'), models.Index(fields=['management_station', 'field_family', 'compact_value'], name='integration_managem_4c04ae_idx'), models.Index(fields=['management_station', 'field_family', 'rule_count'], name='integration_managem_778e34_idx')],
                'constraints': [models.UniqueConstraint(fields=('management_station', 'field_family', 'canonical_value'), name='integrations_unique_security_rule_search_vocab_entry')],
            },
        ),
    ]
