# Generated by Django 6.0.4 on 2026-05-01 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_securityrulesearchvocabularyentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_short_name', models.CharField(max_length=64)),
                ('opportunity_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Opportunity number must be in the format "OP-1234567".', regex='^OP-\\d{7}$')])),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['client_name', 'opportunity_number', 'id'],
            },
        ),
    ]
